services:
  # PostgreSQL
  pg_db:
    image: postgres:15-alpine
    container_name: cloud-postgres
    restart: always
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    networks:
      - cloud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d cloud_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB
  mongo:
    image: mongo:7.0-jammy
    container_name: cloud-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: cloud_metadata
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - cloud-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    command: ["mongod", "--auth"]

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: cloud-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
    driver: local
  mongo_data:      # <-- ДОБАВЛЕНО!
    driver: local
  minio_data:
    driver: local

networks:
  cloud-network:
    driver: bridge