spring.application.name=Cloud
server.port=9096

#settings of postgres
spring.datasource.url=jdbc:postgresql://localhost:5455/cloud_db
spring.datasource.username=docker
spring.datasource.password=docker
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#swagger links
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.oauth.client-id=test
springdoc.swagger-ui.oauth.scopes=openid,profile,email
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

# MinIO settings
spring.cloud.aws.s3.enabled=false
spring.cloud.aws.autoconfigure.skip=true

# MinIO connection
minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket=storage

#http://localhost:9096/swagger-ui/index.html

secret_key=a75e634e8114af0e321cf20165465833148b0f52378d4d1df5da6f38832683b1
#eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbCIsImlhdCI6MTc3MDUzNDkzMiwiZXhwIjoxNzcwNjIxMzMyfQ.UUr8LZs8TzWRuLC4qDZfcJYSASNN6SZiqxLmQZutV8U
